Update Readme.md
meerhamzadev/Hacktoberfest pull request #18
Opened 2022-10-04 12:15 UTC by BTANISHA11

Readme.md updated

2022-10-04 12:15 UTC, BTANISHA11 commented
DONE @meerhamzadev

2022-10-04 12:20 UTC, meerhamzadev commented on README.md
> +4. Click on submit new issue
Since the whole readme is following an emoji pattern for headings. Can you please add distinct emojis to these two headings for consistency?

2022-10-04 12:21 UTC, meerhamzadev requested changes
@BTANISHA11 Since the whole readme is following an emoji pattern for headings. Can you please add distinct emojis to new headings as well for consistency?

2022-10-04 12:35 UTC, BTANISHA11 commented
Changes done @meerhamzadev

2022-10-04 12:40 UTC, meerhamzadev approved these changes
Great work

2022-10-04 12:40 UTC, merged

2022-10-05 04:05 UTC, BTANISHA11 commented
@meerhamzadev on my hacktoberfest profile its showing excluded. Can you pls resolve the issue.